export const LOGIN_INPUT = 'credentials';
export const REFRESH_INPUT = 'refresh';

export const JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET';
export const JWT_ACCESS_TOKEN_SECRET = 'JWT_ACCESS_TOKEN_SECRET';
export const JWT_ACCESS_TOKEN_EXPIRATION_TIME =
  'JWT_ACCESS_TOKEN_EXPIRATION_TIME';
export const JWT_REFRESH_TOKEN_EXPIRATION_TIME =
  'JWT_REFRESH_TOKEN_EXPIRATION_TIME';

export const CREATE_USER_INPUT = 'createUserInput';
